// API 1
//Scenario 1
//Returns a list of all todos whose status is 'TO DO'
GET http://localhost:3000/todos/?status=TO%20DO


###
//Scenario 2
//Returns a list of all todos whose priority is 'HIGH'
GET http://localhost:3000/todos/?priority=HIGH

###
//Scenario 3
//Returns a list of all todos whose priority is 'HIGH' and status is 'IN PROGRESS'
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###
//Scenario 4
//Returns a list of all todos whose todo contains 'Play' text
GET http://localhost:3000/todos/?search_q=Play

###
// API 2
//Returns a specific todo based on the todo ID
GET http://localhost:3000/todos/:todoId/

###
// Create a todo in the todo table, 
//API 3
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###
//API 4
//Updates the details of a specific todo based on the todo ID

//SCENARIO 1
//Status Updated
PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json

{
 "status": "DONE" 
}

###
//SCENARIO 2
//Priority Updated
PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json

{
"priority": "HIGH" 
}

###
//SCENARIO 3
//Todo Updated
PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json

{
 "todo": "Some task"
}

###
// API 5
//Deletes a todo from the todo table based on the todo ID
DELETE http://localhost:3000/todos/:todoId/
